export const GENDERS = {
    MALE: 'male',
    FEMALE: 'female',
    OTHER: 'other',
} as const;

export const COUNTRY_NAMES = {
    UnitedStates: 'United States',
    Afghanistan: 'Afghanistan',
    AlandIslands: 'Aland Islands',
    Albania: 'Albania',
    Algeria: 'Algeria',
    AmericanSamoa: 'American Samoa',
    Andorra: 'Andorra',
    Angola: 'Angola',
    Anguilla: 'Anguilla',
    Antarctica: 'Antarctica',
    AntiguaAndBarbuda: 'Antigua And Barbuda',
    Argentina: 'Argentina',
    Armenia: 'Armenia',
    Aruba: 'Aruba',
    Australia: 'Australia',
    Austria: 'Austria',
    Azerbaijan: 'Azerbaijan',
    Bahamas: 'Bahamas',
    Bahrain: 'Bahrain',
    Bangladesh: 'Bangladesh',
    Barbados: 'Barbados',
    Belarus: 'Belarus',
    Belgium: 'Belgium',
    Belize: 'Belize',
    Benin: 'Benin',
    Bermuda: 'Bermuda',
    Bhutan: 'Bhutan',
    Bolivia: 'Bolivia',
    BonaireSintEustatiusSaba: 'Bonaire Sint Eustatius Saba',
    BosniaAndHerzegovina: 'Bosnia And Herzegovina',
    Botswana: 'Botswana',
    BouvetIsland: 'Bouvet Island',
    Brazil: 'Brazil',
    BritishIndianOceanTerritory: 'British Indian Ocean Territory',
    BruneiDarussalam: 'Brunei Darussalam',
    Bulgaria: 'Bulgaria',
    BurkinaFaso: 'Burkina Faso',
    Burundi: 'Burundi',
    Cambodia: 'Cambodia',
    Cameroon: 'Cameroon',
    Canada: 'Canada',
    CapeVerde: 'Cape Verde',
    CaymanIslands: 'Cayman Islands',
    CentralAfricanRepublic: 'Central African Republic',
    Chad: 'Chad',
    Chile: 'Chile',
    China: 'China',
    ChristmasIsland: 'Christmas Island',
    CocosKeelingIslands: 'Cocos Keeling Islands',
    Colombia: 'Colombia',
    Comoros: 'Comoros',
    Congo: 'Congo',
    CongoDemocraticRepublic: 'Congo Democratic Republic',
    CookIslands: 'Cook Islands',
    CostaRica: 'Costa Rica',
    CoteDIvoire: 'Cote DIvoire',
    Croatia: 'Croatia',
    Cuba: 'Cuba',
    Curaçao: 'Curaçao',
    Cyprus: 'Cyprus',
    CzechRepublic: 'Czech Republic',
    Denmark: 'Denmark',
    Djibouti: 'Djibouti',
    Dominica: 'Dominica',
    DominicanRepublic: 'Dominican Republic',
    Ecuador: 'Ecuador',
    Egypt: 'Egypt',
    ElSalvador: 'El Salvador',
    EquatorialGuinea: 'Equatorial Guinea',
    Eritrea: 'Eritrea',
    Estonia: 'Estonia',
    Ethiopia: 'Ethiopia',
    FalklandIslands: 'Falkland Islands',
    FaroeIslands: 'Faroe Islands',
    Fiji: 'Fiji',
    Finland: 'Finland',
    France: 'France',
    FrenchGuiana: 'French Guiana',
    FrenchPolynesia: 'French Polynesia',
    FrenchSouthernTerritories: 'French Southern Territories',
    Gabon: 'Gabon',
    Gambia: 'Gambia',
    Georgia: 'Georgia',
    Germany: 'Germany',
    Ghana: 'Ghana',
    Gibraltar: 'Gibraltar',
    Greece: 'Greece',
    Greenland: 'Greenland',
    Grenada: 'Grenada',
    Guadeloupe: 'Guadeloupe',
    Guam: 'Guam',
    Guatemala: 'Guatemala',
    Guernsey: 'Guernsey',
    Guinea: 'Guinea',
    GuineaBissau: 'Guinea Bissau',
    Guyana: 'Guyana',
    Haiti: 'Haiti',
    HeardIslandMcdonaldIslands: 'Heard Island Mcdonald Islands',
    HolySeeVaticanCityState: 'Holy See Vatican City State',
    Honduras: 'Honduras',
    HongKong: 'Hong Kong',
    Hungary: 'Hungary',
    Iceland: 'Iceland',
    India: 'India',
    Indonesia: 'Indonesia',
    Iran: 'Iran',
    Iraq: 'Iraq',
    Ireland: 'Ireland',
    IsleOfMan: 'Isle Of Man',
    Israel: 'Israel',
    Italy: 'Italy',
    Jamaica: 'Jamaica',
    Japan: 'Japan',
    Jersey: 'Jersey',
    Jordan: 'Jordan',
    Kazakhstan: 'Kazakhstan',
    Kenya: 'Kenya',
    Kiribati: 'Kiribati',
    Korea: 'Korea',
    KoreaDemocraticPeoplesRepublic: 'Korea Democratic Peoples Republic',
    Kuwait: 'Kuwait',
    Kyrgyzstan: 'Kyrgyzstan',
    LaoPeoplesDemocraticRepublic: 'Lao Peoples Democratic Republic',
    Latvia: 'Latvia',
    Lebanon: 'Lebanon',
    Lesotho: 'Lesotho',
    Liberia: 'Liberia',
    LibyanArabJamahiriya: 'Libyan Arab Jamahiriya',
    Liechtenstein: 'Liechtenstein',
    Lithuania: 'Lithuania',
    Luxembourg: 'Luxembourg',
    Macao: 'Macao',
    Macedonia: 'Macedonia',
    Madagascar: 'Madagascar',
    Malawi: 'Malawi',
    Malaysia: 'Malaysia',
    Maldives: 'Maldives',
    Mali: 'Mali',
    Malta: 'Malta',
    MarshallIslands: 'Marshall Islands',
    Martinique: 'Martinique',
    Mauritania: 'Mauritania',
    Mauritius: 'Mauritius',
    Mayotte: 'Mayotte',
    Mexico: 'Mexico',
    Micronesia: 'Micronesia',
    Moldova: 'Moldova',
    Monaco: 'Monaco',
    Mongolia: 'Mongolia',
    Montenegro: 'Montenegro',
    Montserrat: 'Montserrat',
    Morocco: 'Morocco',
    Mozambique: 'Mozambique',
    Myanmar: 'Myanmar',
    Namibia: 'Namibia',
    Nauru: 'Nauru',
    Nepal: 'Nepal',
    Netherlands: 'Netherlands',
    NewCaledonia: 'New Caledonia',
    NewZealand: 'New Zealand',
    Nicaragua: 'Nicaragua',
    Niger: 'Niger',
    Nigeria: 'Nigeria',
    Niue: 'Niue',
    NorfolkIsland: 'Norfolk Island',
    NorthernMarianaIslands: 'Northern Mariana Islands',
    Norway: 'Norway',
    Oman: 'Oman',
    Pakistan: 'Pakistan',
    Palau: 'Palau',
    PalestinianTerritory: 'Palestinian Territory',
    Panama: 'Panama',
    PapuaNewGuinea: 'Papua New Guinea',
    Paraguay: 'Paraguay',
    Peru: 'Peru',
    Philippines: 'Philippines',
    Pitcairn: 'Pitcairn',
    Poland: 'Poland',
    Portugal: 'Portugal',
    PuertoRico: 'Puerto Rico',
    Qatar: 'Qatar',
    Reunion: 'Reunion',
    Romania: 'Romania',
    RussianFederation: 'Russian Federation',
    Rwanda: 'Rwanda',
    SaintBarthelemy: 'Saint Barthelemy',
    SaintHelena: 'Saint Helena',
    SaintKittsAndNevis: 'Saint Kitts And Nevis',
    SaintLucia: 'Saint Lucia',
    SaintMartin: 'Saint Martin',
    SaintPierreAndMiquelon: 'Saint Pierre And Miquelon',
    SaintVincentAndGrenadines: 'Saint Vincent And Grenadines',
    Samoa: 'Samoa',
    SanMarino: 'San Marino',
    SaoTomeAndPrincipe: 'Sao Tome And Principe',
    SaudiArabia: 'Saudi Arabia',
    Senegal: 'Senegal',
    Serbia: 'Serbia',
    Seychelles: 'Seychelles',
    SierraLeone: 'Sierra Leone',
    Singapore: 'Singapore',
    SintMaarten: 'Sint Maarten',
    Slovakia: 'Slovakia',
    Slovenia: 'Slovenia',
    SolomonIslands: 'Solomon Islands',
    Somalia: 'Somalia',
    SouthAfrica: 'South Africa',
    SouthGeorgiaAndSandwichIsl: 'South Georgia And SandwichIsl',
    SouthSudan: 'South Sudan',
    Spain: 'Spain',
    SriLanka: 'Sri Lanka',
    Sudan: 'Sudan',
    Suriname: 'Suriname',
    SvalbardAndJanMayen: 'Svalbard And Jan Mayen',
    Swaziland: 'Swaziland',
    Sweden: 'Sweden',
    Switzerland: 'Switzerland',
    SyrianArabRepublic: 'Syrian Arab Republic',
    Taiwan: 'Taiwan',
    Tajikistan: 'Tajikistan',
    Tanzania: 'Tanzania',
    Thailand: 'Thailand',
    TimorLeste: 'Timor Leste',
    Togo: 'Togo',
    Tokelau: 'Tokelau',
    Tonga: 'Tonga',
    TrinidadAndTobago: 'Trinidad And Tobago',
    Tunisia: 'Tunisia',
    Turkey: 'Turkey',
    Turkmenistan: 'Turkmenistan',
    TurksAndCaicosIslands: 'Turks And Caicos Islands',
    Tuvalu: 'Tuvalu',
    Uganda: 'Uganda',
    Ukraine: 'Ukraine',
    UnitedArabEmirates: 'United Arab Emirates',
    UnitedKingdom: 'United Kingdom',
    UnitedStatesOutlyingIslands: 'United States Outlying Islands',
    Uruguay: 'Uruguay',
    Uzbekistan: 'Uzbekistan',
    Vanuatu: 'Vanuatu',
    Venezuela: 'Venezuela',
    VietNam: 'Vietnam',
    VirginIslandsBritish: 'Virgin Islands British',
    VirginIslandsUS: 'Virgin Islands US',
    WallisAndFutuna: 'Wallis And Futuna',
    WesternSahara: 'Western Sahara',
    Yemen: 'Yemen',
    Zambia: 'Zambia',
    Zimbabwe: 'Zimbabwe',
} as const;

export const COUNTRY_CODES = {
    UnitedStates: 'us',
    Afghanistan: 'af',
    AlandIslands: 'ax',
    Albania: 'al',
    Algeria: 'dz',
    AmericanSamoa: 'as',
    Andorra: 'ad',
    Angola: 'ao',
    Anguilla: 'ai',
    Antarctica: 'aq',
    AntiguaAndBarbuda: 'ag',
    Argentina: 'ar',
    Armenia: 'am',
    Aruba: 'aw',
    Australia: 'au',
    Austria: 'at',
    Azerbaijan: 'az',
    Bahamas: 'bs',
    Bahrain: 'bh',
    Bangladesh: 'bd',
    Barbados: 'bb',
    Belarus: 'by',
    Belgium: 'be',
    Belize: 'bz',
    Benin: 'bj',
    Bermuda: 'bm',
    Bhutan: 'bt',
    Bolivia: 'bo',
    BonaireSintEustatiusSaba: 'bq',
    BosniaAndHerzegovina: 'ba',
    Botswana: 'bw',
    BouvetIsland: 'bv',
    Brazil: 'br',
    BritishIndianOceanTerritory: 'io',
    BruneiDarussalam: 'bn',
    Bulgaria: 'bg',
    BurkinaFaso: 'bf',
    Burundi: 'bi',
    Cambodia: 'kh',
    Cameroon: 'cm',
    Canada: 'ca',
    CapeVerde: 'cv',
    CaymanIslands: 'ky',
    CentralAfricanRepublic: 'cf',
    Chad: 'td',
    Chile: 'cl',
    China: 'cn',
    ChristmasIsland: 'cx',
    CocosKeelingIslands: 'cc',
    Colombia: 'co',
    Comoros: 'km',
    Congo: 'cg',
    CongoDemocraticRepublic: 'cd',
    CookIslands: 'ck',
    CostaRica: 'cr',
    CoteDIvoire: 'ci',
    Croatia: 'hr',
    Cuba: 'cu',
    Curaçao: 'cw',
    Cyprus: 'cy',
    CzechRepublic: 'cz',
    Denmark: 'dk',
    Djibouti: 'dj',
    Dominica: 'dm',
    DominicanRepublic: 'do',
    Ecuador: 'ec',
    Egypt: 'eg',
    ElSalvador: 'sv',
    EquatorialGuinea: 'gq',
    Eritrea: 'er',
    Estonia: 'ee',
    Ethiopia: 'et',
    FalklandIslands: 'fk',
    FaroeIslands: 'fo',
    Fiji: 'fj',
    Finland: 'fi',
    France: 'fr',
    FrenchGuiana: 'gf',
    FrenchPolynesia: 'pf',
    FrenchSouthernTerritories: 'tf',
    Gabon: 'ga',
    Gambia: 'gm',
    Georgia: 'ge',
    Germany: 'de',
    Ghana: 'gh',
    Gibraltar: 'gi',
    Greece: 'gr',
    Greenland: 'gl',
    Grenada: 'gd',
    Guadeloupe: 'gp',
    Guam: 'gu',
    Guatemala: 'gt',
    Guernsey: 'gg',
    Guinea: 'gn',
    GuineaBissau: 'gw',
    Guyana: 'gy',
    Haiti: 'ht',
    HeardIslandMcdonaldIslands: 'hm',
    HolySeeVaticanCityState: 'va',
    Honduras: 'hn',
    HongKong: 'hk',
    Hungary: 'hu',
    Iceland: 'is',
    India: 'in',
    Indonesia: 'id',
    Iran: 'ir',
    Iraq: 'iq',
    Ireland: 'ie',
    IsleOfMan: 'im',
    Israel: 'il',
    Italy: 'it',
    Jamaica: 'jm',
    Japan: 'jp',
    Jersey: 'je',
    Jordan: 'jo',
    Kazakhstan: 'kz',
    Kenya: 'ke',
    Kiribati: 'ki',
    Korea: 'kr',
    KoreaDemocraticPeoplesRepublic: 'kp',
    Kuwait: 'kw',
    Kyrgyzstan: 'kg',
    LaoPeoplesDemocraticRepublic: 'la',
    Latvia: 'lv',
    Lebanon: 'lb',
    Lesotho: 'ls',
    Liberia: 'lr',
    LibyanArabJamahiriya: 'ly',
    Liechtenstein: 'li',
    Lithuania: 'lt',
    Luxembourg: 'lu',
    Macao: 'mo',
    Macedonia: 'mk',
    Madagascar: 'mg',
    Malawi: 'mw',
    Malaysia: 'my',
    Maldives: 'mv',
    Mali: 'ml',
    Malta: 'mt',
    MarshallIslands: 'mh',
    Martinique: 'mq',
    Mauritania: 'mr',
    Mauritius: 'mu',
    Mayotte: 'yt',
    Mexico: 'mx',
    Micronesia: 'fm',
    Moldova: 'md',
    Monaco: 'mc',
    Mongolia: 'mn',
    Montenegro: 'me',
    Montserrat: 'ms',
    Morocco: 'ma',
    Mozambique: 'mz',
    Myanmar: 'mm',
    Namibia: 'na',
    Nauru: 'nr',
    Nepal: 'np',
    Netherlands: 'nl',
    NewCaledonia: 'nc',
    NewZealand: 'nz',
    Nicaragua: 'ni',
    Niger: 'ne',
    Nigeria: 'ng',
    Niue: 'nu',
    NorfolkIsland: 'nf',
    NorthernMarianaIslands: 'mp',
    Norway: 'no',
    Oman: 'om',
    Pakistan: 'pk',
    Palau: 'pw',
    PalestinianTerritory: 'ps',
    Panama: 'pa',
    PapuaNewGuinea: 'pg',
    Paraguay: 'py',
    Peru: 'pe',
    Philippines: 'ph',
    Pitcairn: 'pn',
    Poland: 'pl',
    Portugal: 'pt',
    PuertoRico: 'pr',
    Qatar: 'qa',
    Reunion: 're',
    Romania: 'ro',
    RussianFederation: 'ru',
    Rwanda: 'rw',
    SaintBarthelemy: 'bl',
    SaintHelena: 'sh',
    SaintKittsAndNevis: 'kn',
    SaintLucia: 'lc',
    SaintMartin: 'mf',
    SaintPierreAndMiquelon: 'pm',
    SaintVincentAndGrenadines: 'vc',
    Samoa: 'ws',
    SanMarino: 'sm',
    SaoTomeAndPrincipe: 'st',
    SaudiArabia: 'sa',
    Senegal: 'sn',
    Serbia: 'rs',
    Seychelles: 'sc',
    SierraLeone: 'sl',
    Singapore: 'sg',
    SintMaarten: 'sx',
    Slovakia: 'sk',
    Slovenia: 'si',
    SolomonIslands: 'sb',
    Somalia: 'so',
    SouthAfrica: 'za',
    SouthGeorgiaAndSandwichIsl: 'gs',
    SouthSudan: 'ss',
    Spain: 'es',
    SriLanka: 'lk',
    Sudan: 'sd',
    Suriname: 'sr',
    SvalbardAndJanMayen: 'sj',
    Swaziland: 'sz',
    Sweden: 'se',
    Switzerland: 'ch',
    SyrianArabRepublic: 'sy',
    Taiwan: 'tw',
    Tajikistan: 'tj',
    Tanzania: 'tz',
    Thailand: 'th',
    TimorLeste: 'tl',
    Togo: 'tg',
    Tokelau: 'tk',
    Tonga: 'to',
    TrinidadAndTobago: 'tt',
    Tunisia: 'tn',
    Turkey: 'tr',
    Turkmenistan: 'tm',
    TurksAndCaicosIslands: 'tc',
    Tuvalu: 'tv',
    Uganda: 'ug',
    Ukraine: 'ua',
    UnitedArabEmirates: 'ae',
    UnitedKingdom: 'gb',
    UnitedStatesOutlyingIslands: 'um',
    Uruguay: 'uy',
    Uzbekistan: 'uz',
    Vanuatu: 'vu',
    Venezuela: 've',
    VietNam: 'vn',
    VirginIslandsBritish: 'vg',
    VirginIslandsUS: 'vi',
    WallisAndFutuna: 'wf',
    WesternSahara: 'eh',
    Yemen: 'ye',
    Zambia: 'zm',
    Zimbabwe: 'zw',
} as const;
