apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env-config
  namespace: {{ .Release.Namespace | default "uptime-monitor" }}
data:
  env_{{ .Values.env_type }}: |-
    {{ .Values.configMap.data.env_file | nindent 4 }}
